INSERT INTO TB_CATEGORY (NAME, created_At) VALUES ('BOOKS', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES ('COMPUTER', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES ('ELETRONICS', NOW());